language: node_js
node_js:
  - '12'
before_install:
  # Update the npm client. Older clients cannot, e.g., handle scoped modules.
  - npm update -g npm
after_script:
  - npm run coverage
  - npm start
